/* ARTICLE */
// Post
export const ARTICLE_POST = 'ARTICLE_POST';
export const ARTICLE_POST_FAILURE = 'ARTICLE_POST_FAILURE';
export const ARTICLE_POST_SUCCESS = 'ARTICLE_POST_SUCCESS';
export const ARTICLE_POST_VALUE = 'ARTICLE_POST_VALUE';